### ISSUE TITLE
There is no result returned from `push_blob`

### ISSUE THREAD

**Issue by mbeilin** [datopian/ckan3-py-sdk#21]
There is no result returned from `push_blob` in case the file is new (not exists in storage):
https://github.com/datopian/ckan-client-py/blob/485401443d07320954fe627bc47b0c0e66f071b9/ckanclient/__init__.py#L181-L183

**Comment by rufuspollock** [comment]
@mbeilin what do you think should be returned?

**Comment by mbeilin** [comment]
> @mbeilin what do you think should be returned?

Something like it was returned previously I think:
https://github.com/datopian/ckan-client-py/blob/1aac214ac6023682d97c27ddc6e10f621583a905/ckan_sdk/client.py#L150-L164

**Comment by cuducos** [comment]
cc @mariorodeghiero just in case this change is also interesting for the JS client : )
