### ISSUE TITLE
Core "push" API

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckan3-py-sdk#6]
I want to push a file (or set of files i.e. a dataset) to a CKAN instance in one command.

Main job stories:

* I want to upload a single file to cloud storage
* I want to "push" a resource to CKAN: upload to storage and add metadata
  * Create new (dataset)
  * Add to existing dataset (as new resource)
  * Replace an existing resource (?)
* I want to push a dataset to CKAN: i.e. multiple files (and metadata)
  * Create new dataset
  * Update an existing dataset (with additional files)
  * Later we could get "clever" and auto push a directory but for now let's make that explicit.

## Design

Insights:

* Separate code for generating a Frictionless Dataset or Resource from the Push code ...
* Focus library on the pushing (and getting) on assumption what you are working with are Frictionless objects
  * Have a simple helper lib for f11s object generation. Follow https://github.com/datopian/data.js

### Porcelain

```python
import ckanclient
# for now this is probably a utility in this lib
# later this can factor out into a f11s lib that does core stuff
import ckanclient.f11s as f11s

# API key/token
config = {
    apiUrl: 'http://datahub.io/',
    token: 'api key',
    debug: false,
    # your default org/owner to use
    ownerid: 'userId',
}
client = new ckanclient.Client(config)

path = '/path/to/file'
resource = f11s.load(path)
print(resource)
  {
    path: ...
    sha256: ...
    bytes: ...
  }

dataset = f11s.Dataset({
  'name': 'xxx'
  })
dataset.addResource(resource)

# TODO: does this convert to a dataset before pushing?
# would have to internally ... (would be better to then be explicit ...)
res = await client.push(dataset)
print(res)
{
  # result would look something like this
  success: True,
  errors: [],
  dataset_id: ...
}

# just push a resource
res = client.push_resource(resource, dataset='dataset-name', meta_data={'maintainer_email'})

## LATER
# this retrieves the existing dataset first and adds the resource ...
client.push_resource(resource, dataset='dataset-name', append=True)
# dataset = client.get('dataset')
# dataset.addResource(resource)
# client.push(dataset)
```

### Plumbing

```python
# push to cloud storage (don't push to CKAN)
resource = load('/path/to/file')
print(resource)
{
  "path": '/path/to/file',
  sha256: ...
  ...
}
Client.store_blob(file) => return {
  # result would look something like this
  success: True,
  errors: [],
  uploaded_url: ...
}

# this does conversion of f11s to ckan and then can use ckanapi ...
Client.push_metadata(dataset)
## f2c(metadata)
## then upsert: ckanapi.package_create or package_update if exists
## LATER: we can do upsert with merging maybe ...
## ckanapi.package_upsert(metadata)
## see https://gitlab.com/datopian/experiments/nhs-tools/-/blob/master/process.py#L289
```

### f11s

Create a f11s lib OR just use https://github.com/frictionlessdata/datapackage-py

Even if use `datapackage-py` you could provide a wrapper e.g.

`open(path) => return datapackage.Resource(path)`

This is overall API like behaviour:

```python
open(file path) => dict (or more complex Resource with descriptor attribute)

Resource(descriptor)

Dataset.open(path to directory or a datapackage.json)
Dataset(descriptor)
```

**Comment by uwaheed88** [comment]
@rufuspollock I get the main idea that we are going to extend the push function functionality
(currently, my push function is first to get the jwt_auth_token from ckanext-authz, then send batch API request to Git LFS to get upload/verify actions, then upload the resource to the cloud storage). Now we target that it should be capable of creating a data set too before uploading the resource to cloud storage.

I have a question regarding metadata where exactly we are going to store it? Do we add metadata on CKAN instance would we be using metastore-lib or some other package for creating datapackage.json and .lfs pointers?

**Comment by rufuspollock** [comment]
@uwaheed88 updated description with a lot more detail.

**Comment by rufuspollock** [comment]
@uwaheed88 can we close this now do you think or not?

**Comment by rufuspollock** [comment]
FIXED. All working.
